### actor-index
GET http://localhost:3000/actors.json

### actor-create
POST http://localhost:3000/actors.json
Autorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTAzNzMzMTN9.RszTCbWdZRwrwFgl79GUqIXeDm6XyuZH8ZDLIFRdxTI
Content-Type: application/json

{
  "first_name": "Fred",
  "last_name": "Rogers",
  "known_for": "Mister Rogers Neighborhood"
}

### actor-show
GET http://localhost:3000/actors/1.json/

### actor-update
PATCH http://localhost:3000/actors/8.json/
Content-Type: application/json

{
  "first_name": "Michael"
}

### actor-destroy
DELETE http://localhost:3000/actors/8.json/

### show-index
GET http://localhost:3000/shows.json

### show-create
POST http://localhost:3000/shows.json
Content-Type: application/json

{
  "title": "Survivor",
  "year": 2000,
  "plot": "18 strangers stranded on an island trying to win a million dollars"
}

### show-show
GET http://localhost:3000/shows/6.json

### show-update
PATCH http://localhost:3000/shows/6.json
Content-Type: application/json

{
  "plot": "20 strangers stranded on an island trying to win a million dollars"
}

### show-destroy
DELETE http://localhost:3000/shows/6.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Meredith Grey",
  "email": "mgrey@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mgrey@test.com",
  "password": "password"
}