### actor-index
GET http://localhost:3000/actors.json

### actor-create
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Katey",
  "last_name": "Sagal",
  "known_for": "Sons of Anarchy"
}

### actor-show
GET http://localhost:3000/actors/1.json/

### actor-update
PATCH http://localhost:3000/actors/8.json/
Content-Type: application/json

{
  "first_name": "Michael"
}

### actor-destroy
DELETE http://localhost:3000/actors/8.json/

### show-index
GET http://localhost:3000/shows.json

### show-create
POST http://localhost:3000/shows.json
Content-Type: application/json

{
  "title": "Survivor",
  "year": 2000,
  "plot": "18 strangers stranded on an island trying to win a million dollars"
}

### show-show
GET http://localhost:3000/shows/6.json

### show-update
PATCH http://localhost:3000/shows/6.json
Content-Type: application/json

{
  "plot": "20 strangers stranded on an island trying to win a million dollars"
}

### show-destroy
DELETE http://localhost:3000/shows/6.json
